name: youtube_short_masked

steps:
  - download:
      url: https://www.youtube.com/watch?v=aWOggDZHLd4

  - trim:
      start: 10
      end: 2541.0

  - resize:
      preset: shorts

  - overlay:
      source: assets/overlays/yellow.jpg
      position:
        x: center
        y: center
      scale: 1.3
      opacity: 1.0
      mask:
        type: ellipse
        feather: 60
        invert: true

  - encode: {}

  - export:
      output: output/short_masked.mp4